const booksData = [
    {
        id: 1,
        title: "Ikigai: The Japanese Secret To A Long And Happy Life",
        author: "Héctor García & Francesc Miralles",
        imageUrl: "https://img.bookchor.com/images/cover/bc/9781786330895_1.jpg",
        description: "A guide to finding your purpose in life and achieving true happiness.",
        price: "299",
    },
    {
        id: 2,
        title: "RICH DAD POOR DAD",
        author: "Robert T. Kiyosaki",
        imageUrl: "https://img.bookchor.com/images/cover/bc/9781612681139_16600183430.jpg",
        description: "A personal finance classic that offers financial advice and insights.",
        price: "399",
    },
    {
        id: 3,
        title: "Atomic Habits: An Easy And Proven Way To Build Good Habits And Break Bad Ones",
        author: "James Clear",
        imageUrl: "https://img.bookchor.com/images/cover/bc/9781847941831_1.jpg",
        description: "A practical guide to building good habits and breaking bad ones.",
        price: "499",
    },
    {
        id: 4,
        title: "The Courage To Be Disliked",
        author: "Ichiro Kishimi & Fumitake Koga",
        imageUrl: "https://img.bookchor.com/images/cover/bc/9781760630720_17199011510.jpg",
        description: "A book about personal growth and overcoming fear.",
        price: "350",
    },
    {
        id: 5,
        title: "Verity: The Thriller That Will Capture Your Heart And Blow Your Mind",
        author: "Colleen Hoover",
        imageUrl: "https://img.bookchor.com/images/cover/bc/9781408726600_16548429380.jpg",
        description: "A psychological thriller that will keep you on the edge of your seat.",
        price: "450",
    },
    {
        id: 6,
        title: "Sapiens: A Brief History Of Humankind",
        author: "Yuval Noah Harari",
        imageUrl: "https://img.bookchor.com/images/cover/591/9780099590088.jpg",
        description: "A fascinating exploration of the history and impact of Homo sapiens.",
        price: "550",
    },
    {
        id: 7,
        title: "The Alchemist",
        author: "Paulo Coelho",
        imageUrl: "https://img.bookchor.com/images/cover/bc/9788172234980.jpg",
        description: "A novel about a young shepherd's journey to find his personal legend.",
        price: "299",
    },
    {
        id: 8,
        title: "Deep Work: Rules For Focused Success In A Distracted World",
        author: "Cal Newport",
        imageUrl: "https://img.bookchor.com/images/cover/595/9780349413686.jpg",
        description: "A guide to achieving focused success in a world full of distractions.",
        price: "399",
    },
    {
        id: 9,
        title: "11 Rules For Life: Secrets To Level Up",
        author: "Kunal Narayan",
        imageUrl: "https://img.bookchor.com/images/cover/bc/9789356999978_1.jpg",
        description: "Rules and strategies for personal development and growth.",
        price: "399",
    },
    {
        id: 10,
        title: "Diary Of A Wimpy Kid: No Brainer (Book 18)",
        author: "Jeff Kinney",
        imageUrl: "https://img.bookchor.com/images/cover/bc/9780241583135.jpg",
        description: "The latest installment in the popular Diary Of A Wimpy Kid series.",
        price: "250",
    }
];

export default booksData;
